SELECT to_Char(SALES_DATE,'yyyy-mm-dd') as SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
where to_char(SALES_DATE,'yyyy-mm')='2022-03'

UNION ALL

SELECT to_Char(SALES_DATE,'yyyy-mm-dd') as SALES_DATE, PRODUCT_ID, NULL as USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
where to_char(SALES_DATE,'yyyy-mm')='2022-03'
ORDER BY SALES_DATE, PRODUCT_ID,USER_ID