SELECT t.ITEM_ID, i.ITEM_NAME, i.RARITY
FROM ITEM_INFO i JOIN ITEM_TREE t 
ON t.ITEM_ID=i.ITEM_ID
WHERE t.PARENT_ITEM_ID in (SELECT ITEM_ID FROM ITEM_INFO  WHERE RARITY = 'RARE') and
t.PARENT_ITEM_ID is not null
ORDER BY ITEM_ID DESC
