SELECT ID, GENOTYPE, (SELECT GENOTYPE FROM ECOLI_DATA
            WHERE a.PARENT_ID=ID) AS PARENT_GENOTYPE
FROM ECOLI_DATA a
WHERE PARENT_ID is not null and
GENOTYPE & (SELECT GENOTYPE FROM ECOLI_DATA
            WHERE a.PARENT_ID=ID) = (SELECT GENOTYPE FROM ECOLI_DATA
            WHERE a.PARENT_ID=ID)

        